repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer

  # - repo: https://github.com/gruntwork-io/pre-commit
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.1
    hooks:
      - id: terraform_fmt
        description: runs terraform fmt
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
      - id: terraform_tflint
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
